import React from "react";
import "./AboutUs.css";

const AboutUs = () => {
  return (
    <div className="about__us">
      <h1 className="about__title">
        Welcome to Madame Oracle: <br /> The Cosmic Guide
      </h1>
      <div className="about__top-section">
        <h2 className="about__section-title"> Meet Madame Oracle:</h2>
        <p>
          This is not your typical fortune teller. She is a cosmic guide, a
          digital oracle that draws from the stars to provide you with
          personalized insights. Utilizing advanced AI algorithms, Madame Oracle
          interprets the positioning of the stars at your birth and compares
          them with their current alignment, offering a glimpse into your cosmic
          blueprint.
        </p>
      </div>
      <div className="aboout__bottom-section">
        <h2 className="about__section-title">How it works</h2>
        <p className="about__paragraph">
          <span className="step">Step 1:</span> Register
          <br />
          Create your profile using your date and place of birth. Madame Oracle
          offers personalized readings in multiple languages, embracing diverse
          cultures for an inclusive experience.
        </p>
        <p className="about__paragraph">
          <span className="step">Step 2:</span> Interact with The Cosmic Ball
          <br />
          Click and hold on the cosmic ball to speak with Madame Oracle. Make
          sure to hold down until you finish asking your question to ensure she
          hears you completely.
        </p>
        <p className="about__paragraph">
          <span className="step">Step 3:</span> Send Your Question
          <br />
          After submitting your query, Madame Oracle begins her cosmic
          consultation, providing insights based on your birth chart and the
          stars' current alignment.
        </p>
        <p className="about__paragraph">
          <span className="step">Step 4:</span> Receive Your Personalized
          Reading
          <br />
          Listen attentively as Madame Oracle interprets the stars and offers
          her cosmic wisdom tailored to your inquiry.
        </p>
        <p className="about__paragraph">
          <span className="step">Step 5:</span>Step 5: Save and Share Your
          Reading
          <br />
          Post-reading, you can save it to your profile for later reference or
          share the insights with friends and family.
        </p>
        <h3 className="about__section-title">Disclaimer:</h3>
        <p className="about__paragraph">
          <span className="step">FOR ENTERTAINMENT PURPOSES ONLY</span>
          <br />
          The readings and insights provided by Madame Oracle are for
          entertainment purposes only. While we strive for accuracy, we do not
          claim that our readings reflect scientific precision. The content
          should not be taken as literal or factual advice. We do not provide
          recommendations on health, legal, financial, or other specific
          professional matters. Users are advised to use their discretion and
          consult qualified professionals for advice on such topics.
          <br />
          <br />
          <span className="step">Voice Disclaimer:</span>
          <br />
          The voice you hear from Madame Oracle is generated by "Alloy", an
          advanced AI, and does not represent a real person.
        </p>
      </div>
    </div>
  );
};

export default AboutUs;
