const madameOracleQuestions = [
    "What secrets lie in your stars?",
    "How do your birth stars guide you?",
    "Which celestial energies influence you now?",
    "What do constellations say about your path?",
    "What guidance do the planets offer you?",
    "How can the cosmos illuminate your challenges?",
    "What do the stars reveal about your desires?",
    "What cosmic guidance do you seek?",
    "What messages do the planets hold for you?",
    "How does astrology illuminate your life purpose?",
    "What insights does your birth chart provide?",
    "What do current star alignments suggest?",
    "What cosmic patterns surround you now?",
    "How do the stars align with your opportunities?",
    "What wisdom do the stars offer your heart?",
    "Which astrological traits resonate with you?",
    "How do your stars enhance self-awareness?",
    "What cosmic advice harmonizes relationships?",
    "What answers does the universe hold for you?",
    "What do your birth stars whisper?",
    "Which celestial sign guides your way?",
    "What do the planets reveal about you?",
    "Where do the stars lead your journey?",
    "What cosmic truths await your discovery?",
    "How do the heavens reflect in your life?",
    "What astral advice shapes your path?",
    "Which stellar secrets can enlighten you?",
    "How do celestial patterns influence you?",
    "What universal wisdom speaks to you?",
    "How do the stars align with your dreams?",
    "What insights do the constellations offer?",
    "Which cosmic forces impact you now?",
    "What celestial wisdom aids your quest?",
    "How can the cosmos clarify your choices?",
    "What star-born insights resonate with you?",
    "Which cosmic alignment shapes your destiny?",
    "What does the universe whisper to your soul?",
    "How can starlight illuminate your decisions?"
  ];
  
  export { madameOracleQuestions };